# Generated by Django 4.1 on 2022-09-05 17:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=50)),
                ("growth_time", models.IntegerField(blank=True)),
                ("max_harvest", models.IntegerField(blank=True)),
                ("natural_gift_power", models.IntegerField(blank=True)),
                ("size", models.IntegerField(blank=True)),
                ("smoothness", models.IntegerField(blank=True)),
                ("soil_dryness", models.IntegerField(blank=True)),
                (
                    "date_published",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                ("potency", models.IntegerField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
