# Generated by Django 4.1 on 2022-09-05 20:37

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Pokeapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonTrainer",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=50)),
                ("age", models.FloatField(blank=True)),
                ("origin_city", models.CharField(blank=True, max_length=100)),
                ("gender", models.CharField(max_length=3)),
                ("region_name", models.CharField(max_length=100)),
                ("is_training", models.BooleanField()),
                (
                    "pokemon",
                    models.ManyToManyField(
                        help_text="Seleccione un Pokemon para éste entrenador",
                        to="Pokeapi.pokemon",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PokemonTeam",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=50)),
                ("origin_city", models.CharField(blank=True, max_length=100)),
                ("region_name", models.CharField(max_length=100)),
                ("number_wins", models.IntegerField(blank=True)),
                (
                    "pokemonTrainer",
                    models.ManyToManyField(
                        help_text="Seleccione un Entrenador para formar un Team",
                        to="Pokeapi.pokemontrainer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
