# Generated by Django 4.1 on 2022-09-06 01:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Pokeapi", "0002_pokemontrainer_pokemonteam"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonTeamOnly",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nameTeam", models.CharField(blank=True, max_length=50)),
                ("onlyPokemon", models.BooleanField()),
                (
                    "pokemon",
                    models.ManyToManyField(
                        help_text="Seleccione un Pokemon para éste entrenador",
                        to="Pokeapi.pokemon",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
