# Generated by Django 4.1 on 2022-09-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pokeapi", "0003_pokemonteamonly"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="Evolution",
            field=models.CharField(
                blank=True,
                help_text="Escriba la evolución siguiente, si no la conoce; déjelo en blanco",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="natural",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="preEvolution",
            field=models.CharField(
                blank=True,
                help_text="Escriba la evolución anterior, si no la conoce; déjelo en blanco",
                max_length=100,
            ),
        ),
    ]
