# Generated by Django 4.1 on 2022-09-06 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Pokeapi", "0004_pokemon_evolution_pokemon_natural_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemon",
            old_name="Evolution",
            new_name="evolution",
        ),
    ]
